quadrantChart
    title "Usability and Performance of Competitive Programming Platforms"
    x-axis "Low Usability" --> "High Usability"
    y-axis "Low Performance" --> "High Performance"
    quadrant-1 "SPOJ"
    quadrant-2 "GeeksforGeeks Practice"
    quadrant-3 "HackerRank Code Challenges"
    quadrant-4 "LeetCode Challenges"
    "Codechef Problem Solvers": [0.7, 0.8]
    "HackerRank Code Challenges": [0.6, 0.6]
    "LeetCode Challenges": [0.5, 0.9]
    "GeeksforGeeks Practice": [0.4, 0.5]
    "SPOJ": [0.3, 0.4]
    "Our Target Product": [0.8, 0.9]